Rework/Enhance help and usage
p-ranav/argparse pull request #187
Opened 2022-07-25 18:06 UTC by ndevenish

Generally reworked help output to be a little more like what I expect (or, at least, like python's argparse)

- Added metavars. If set, then will be used in help for the value placeholder for options, or the placeholder alone for regular positional arguments.
- Help option sections are indented by two spaces, and comma-separated. They now show metavar (this means that an option with value now shows as `--option VALUE     Description of Option` instead of `--option    Description ...`.
- Usage section now enumerates options, instead of just `[options]`. Added `ArgumentParser::usage()` to retreive this string alone (in case you wanted to, say, print usage if arguments incorrectly passed).
- Not showing `[default: ...]` for implicit values. This seemed unusual. It might be better to rework the help system to recognise a placeholder (even python's `%(default)s`) rather than try to magically get this right.
- I've refreshed the README with the updated strings from this approach.

I guess the biggest holes are:
- Multiple argument support is a little underrepresented compared to the full semantics of python's argparse. I don't know how well the approach to multiple arguments in this package matches the semantics of the python package.
- I haven't written tests for this because the help output doesn't seem to be tested. I'm not opposed to writing some.

Otherwise this... might not be how you want things. If you like these changes I'm happy to do some amount of reworking to get it up to scratch for merging - these changes work for my purposes, but it could be that you wanted all of this done some other way. I thought I'd at least try to polish them up if it was useful ;)

---

A slightly expanded version of the README second example:
```c++
  argparse::ArgumentParser program("main");
  program.add_argument("thing").help("Thing to use.").metavar("THING");
  program.add_argument("--member").help("The alias for the member to pass to.").metavar("ALIAS");
  program.add_argument("--verbose").default_value(false).implicit_value(true);
  program.add_description("Forward a thing to the next member.");
  program.add_epilog("Possible things include betingalw, chiz, and res.");
```
Gives:
```
% ./main --help
Usage: main [-h] [--member ALIAS] [--verbose] THING

Forward a thing to the next member.

Positional arguments:
  THING         	Thing to use.

Optional arguments:
  -h, --help    	shows help message and exits
  -v, --version 	prints version information and exits
  --member ALIAS	The alias for the member to pass to.
  --verbose

Possible things include betingalw, chiz, and res.

```

2022-08-01 19:50 UTC, skrobinson requested changes
Overall, I like the feature. Thank you for your work.

I'd like to see a metavar-specific example added to README. This is a nice feature that should be pointed out in the docs.

2022-08-01 19:50 UTC, skrobinson commented on include/argparse/argparse.hpp
> +    const std::string metavar = m_metavar.size() > 0 ? m_metavar : "VAR";
Please use `!m_metavar.empty()`. There are three of these.

2022-08-01 19:50 UTC, skrobinson commented on include/argparse/argparse.hpp
> +        return 2 + names_size + (m_names.size() - 1);
Remove the else after return.

2022-08-01 19:50 UTC, skrobinson commented on include/argparse/argparse.hpp
> +    if (argument.is_positional(argument.m_names.front())) {
`is_positional` is a static member function and does not need an instance.

2022-08-14 11:28 UTC, ndevenish commented
Hi, just a note that I'm happy to make these changes and rework the README, I've just been a little busy and won't be able to get to it for a couple of weeks 😅

2022-09-22 02:18 UTC, p-ranav commented
Refactored and merged as part of https://github.com/p-ranav/argparse/pull/206, including changes requested by @skrobinson. Thanks to both of you!

2022-09-22 02:18 UTC, closed without merging